// SPDX-FileCopyrightText: 2026 Paul Büchner
// SPDX-License-Identifier: MIT

using System;
using System.IO;

// NUnit
using NUnit.Framework;

namespace NetOcc.Generator.Tests;

/// <summary>config/toolkits.yaml from OCCT's own module, toolkit and package lists.</summary>
[TestFixture]
public class BootstrapTests
{
  [Test]
  public void Run_ListsThePackagesOfEachToolkit_LeavesOutDraw()
  {
    // Arrange (Draw, OCCT's test harness, has no lists here: reading them would fail)
    using var occt = new TempDirectory("netocc-gen-bootstrap");
    occt.Write("adm/cmake/version.cmake",
               "set (OCC_VERSION_MAJOR 8)\nset (OCC_VERSION_MINOR 0)\nset (OCC_VERSION_MAINTENANCE 1)\n");
    occt.Write("src/MODULES.cmake",
               "set(OCCT_MODULES\n  FoundationClasses\n  ModelingData\n  Draw\n)\n");
    occt.Write("src/FoundationClasses/TOOLKITS.cmake",
               "set(OCCT_FoundationClasses_LIST_OF_TOOLKITS TKernel TKMath)\n");
    occt.Write("src/FoundationClasses/TKernel/PACKAGES.cmake",
               "set(OCCT_TKernel_LIST_OF_PACKAGES\n  Standard\n  NCollection\n)\n");
    occt.Write("src/FoundationClasses/TKMath/PACKAGES.cmake",
               "set(OCCT_TKMath_LIST_OF_PACKAGES gp)\n");
    occt.Write("src/ModelingData/TOOLKITS.cmake",
               "set(OCCT_ModelingData_LIST_OF_TOOLKITS TKG2d)\n");
    occt.Write("src/ModelingData/TKG2d/PACKAGES.cmake",
               "set(OCCT_TKG2d_LIST_OF_PACKAGES Geom2d)\n");
    var output = occt.Combine("config", "toolkits.yaml");
    using var log = new StringWriter();

    // Act
    var exit = Bootstrap.Run(occt.FullName, output, log);

    // Assert
    using (Assert.EnterMultipleScope())
    {
      Assert.That(exit, Is.Zero);
      Assert.That(File.ReadAllText(output),
                  Is.EqualTo(
                    "# Generated by `netocc-gen bootstrap` from OCCT 8.0.1: src/MODULES.cmake,\n"
                    + "# src/<Module>/TOOLKITS.cmake, src/<Module>/<TK>/PACKAGES.cmake. Do not edit; re-run on OCCT upgrades.\n"
                    + "occt: 8.0.1\nmodules:\n  FoundationClasses:\n    TKernel: [Standard, NCollection]\n    TKMath: [gp]\n"
                    + "  ModelingData:\n    TKG2d: [Geom2d]\n"));
      Assert.That(log.ToString(),
                  Does.StartWith("netocc-gen: OCCT 8.0.1: 3 toolkits, 4 packages -> "));
    }
  }

  [Test]
  public void Run_WithoutAVersionPart_Fails()
  {
    // Arrange (every module is stamped with the version: a part that's missing fails here rather
    // than in build.py)
    using var occt = new TempDirectory("netocc-gen-bootstrap");
    occt.Write("adm/cmake/version.cmake", "set (OCC_VERSION_MAJOR 8)\nset (OCC_VERSION_MINOR 0)\n");
    occt.Write("src/MODULES.cmake", "set(OCCT_MODULES)\n");

    // Act
    Action run = () => Bootstrap.Run(occt.FullName, occt.Combine("toolkits.yaml"), TextWriter.Null);

    // Assert
    Assert.That(run, Throws.InstanceOf<InvalidDataException>()
                  .With.Message.EndsWith(": no OCC_VERSION_MAINTENANCE"));
  }

  [Test]
  public void Run_OutsideAnOcctSourceTree_Fails()
  {
    // Arrange
    using var empty = new TempDirectory("netocc-gen-bootstrap");

    // Act
    Action run = () =>
      Bootstrap.Run(empty.FullName, empty.Combine("toolkits.yaml"), TextWriter.Null);

    // Assert
    Assert.That(
      run, Throws.InvalidOperationException.With.Message.Contains("pass the OCCT source root"));
  }
}
