// SPDX-FileCopyrightText: 2026 Paul Büchner
// SPDX-License-Identifier: MIT

/* CPnts: generated by netocc-gen from OCCT 8.0.1. Don't edit; change the generator or its config. */
%module CPntsModule

%include "NetOcc.i"

%{
#include <CPnts_module.hxx>
%}

#ifndef SWIGIMPORTED
%import "GeomAbs.i"
%import "Standard.i"
%import "NCollection.i"
%import "TCollection.i"
%import "TColStd.i"
%import "gp.i"
%import "TColgp.i"
%import "Geom2d.i"
%import "Geom2dEval.i"
%import "Adaptor2d.i"
%import "Geom.i"
%import "GeomEval.i"
%import "TopAbs.i"
%import "Quantity.i"
%import "OSD.i"
%import "Message.i"
%import "math.i"
%import "Adaptor3d.i"
#endif
%netocc_csimports(using OCC.Core.GeomAbs; using OCC.Core.Standard; using OCC.Core.NCollection; using OCC.Core.TCollection; using OCC.Core.TColStd; using OCC.Core.gp; using OCC.Core.TColgp; using OCC.Core.Geom2d; using OCC.Core.Geom2dEval; using OCC.Core.Adaptor2d; using OCC.Core.Geom; using OCC.Core.GeomEval; using OCC.Core.TopAbs; using OCC.Core.Quantity; using OCC.Core.OSD; using OCC.Core.Message; using OCC.Core.math; using OCC.Core.Adaptor3d;)

%occt_valueclass(CPnts_MyGaussFunction)
%occt_valueclass(CPnts_MyRootFunction)
%occt_valueclass(CPnts_AbscissaPoint)
%occt_valueclass(CPnts_UniformDeflection)
%netocc_address(%arg(double (*)(const double, void* const)))

class CPnts_MyGaussFunction : public math_Function {
public:
  CPnts_MyGaussFunction();
  void Init(NetOcc_Address< double (*)(const double, void* const) > F, void* D);
  bool Value(double X, double& F);
};

class CPnts_MyRootFunction : public math_FunctionWithDerivative {
public:
  CPnts_MyRootFunction();
  void Init(NetOcc_Address< double (*)(const double, void* const) > F, void* D, int Order);
  void Init(double X0, double L);
  void Init(double X0, double L, double Tol);
  bool Value(double X, double& F);
  bool Derivative(double X, double& Df);
  bool Values(double X, double& F, double& Df);
};

class CPnts_AbscissaPoint {
public:
  CPnts_AbscissaPoint();
  CPnts_AbscissaPoint(const Adaptor3d_Curve& C, double Abscissa, double U0, double Resolution);
  CPnts_AbscissaPoint(const Adaptor2d_Curve2d& C, double Abscissa, double U0, double Resolution);
  CPnts_AbscissaPoint(const Adaptor3d_Curve& C, double Abscissa, double U0, double Ui, double Resolution);
  CPnts_AbscissaPoint(const Adaptor2d_Curve2d& C, double Abscissa, double U0, double Ui, double Resolution);
  static double Length(const Adaptor3d_Curve& C);
  static double Length(const Adaptor2d_Curve2d& C);
  static double Length(const Adaptor3d_Curve& C, double Tol);
  static double Length(const Adaptor2d_Curve2d& C, double Tol);
  static double Length(const Adaptor3d_Curve& C, double U1, double U2);
  static double Length(const Adaptor2d_Curve2d& C, double U1, double U2);
  static double Length(const Adaptor3d_Curve& C, double U1, double U2, double Tol);
  static double Length(const Adaptor2d_Curve2d& C, double U1, double U2, double Tol);
  void Init(const Adaptor3d_Curve& C);
  void Init(const Adaptor2d_Curve2d& C);
  void Init(const Adaptor3d_Curve& C, double Tol);
  void Init(const Adaptor2d_Curve2d& C, double Tol);
  void Init(const Adaptor3d_Curve& C, double U1, double U2);
  void Init(const Adaptor2d_Curve2d& C, double U1, double U2);
  void Init(const Adaptor3d_Curve& C, double U1, double U2, double Tol);
  void Init(const Adaptor2d_Curve2d& C, double U1, double U2, double Tol);
  void Perform(double Abscissa, double U0, double Resolution);
  void Perform(double Abscissa, double U0, double Ui, double Resolution);
  void AdvPerform(double Abscissa, double U0, double Ui, double Resolution);
  bool IsDone() const;
  double Parameter() const;
  void SetParameter(double P);
};

class CPnts_UniformDeflection {
public:
  CPnts_UniformDeflection();
  CPnts_UniformDeflection(const Adaptor3d_Curve& C, double Deflection, double Resolution, bool WithControl);
  CPnts_UniformDeflection(const Adaptor2d_Curve2d& C, double Deflection, double Resolution, bool WithControl);
  CPnts_UniformDeflection(const Adaptor3d_Curve& C, double Deflection, double U1, double U2, double Resolution, bool WithControl);
  CPnts_UniformDeflection(const Adaptor2d_Curve2d& C, double Deflection, double U1, double U2, double Resolution, bool WithControl);
  void Initialize(const Adaptor3d_Curve& C, double Deflection, double Resolution, bool WithControl);
  void Initialize(const Adaptor2d_Curve2d& C, double Deflection, double Resolution, bool WithControl);
  void Initialize(const Adaptor3d_Curve& C, double Deflection, double U1, double U2, double Resolution, bool WithControl);
  void Initialize(const Adaptor2d_Curve2d& C, double Deflection, double U1, double U2, double Resolution, bool WithControl);
  bool IsAllDone() const;
  void Next();
  bool More();
  double Value() const;
  gp_Pnt Point() const;
};
