// SPDX-FileCopyrightText: 2026 Paul Büchner
// SPDX-License-Identifier: MIT

/* LDOM: generated by netocc-gen from OCCT 8.0.1. Don't edit; change the generator or its config. */
%module LDOMModule

%include "NetOcc.i"

%{
#include <LDOM_module.hxx>
%}

#ifndef SWIGIMPORTED
%import "Standard.i"
%import "NCollection.i"
%import "TCollection.i"
%import "TColStd.i"
#endif
%netocc_csimports(using OCC.Core.Standard; using OCC.Core.NCollection; using OCC.Core.TCollection; using OCC.Core.TColStd;)

%occt_valueclass(LDOMBasicString)
%occt_valueclass(LDOMString)
%occt_transient(LDOM_MemManager)
%nodefaultctor LDOM_MemManager;
%feature("valuewrapper") LDOM_MemManager;
%occt_valueclass(LDOM_Node)
%occt_valueclass(LDOM_Attr)
%occt_valueclass(LDOM_NodeList)
%occt_valueclass(LDOM_Element)
%occt_valueclass(LDOM_CharacterData)
%occt_valueclass(LDOM_Text)
%occt_valueclass(LDOM_CDATASection)
%occt_valueclass(LDOM_Comment)
%occt_valueclass(LDOM_Document)
%nodefaultctor LDOM_SBuffer;
%feature("valuewrapper") LDOM_SBuffer;
%nodefaultctor LDOM_OSStream;
%feature("valuewrapper") LDOM_OSStream;
%nodefaultctor LDOM_BasicNode;
%feature("valuewrapper") LDOM_BasicNode;
%feature("valuewrapper") LDOM_BasicAttribute;
%feature("valuewrapper") LDOM_BasicText;
%occt_valueclass(LDOM_CharReference)
%occt_valueclass(LDOM_DocumentType)
%occt_valueclass(LDOM_LDOMImplementation)
%nodefaultctor LDOM_XmlReader;
%feature("valuewrapper") LDOM_XmlReader;

enum class LDOMBasicString_StringType {
  LDOM_NULL = 0,
  LDOM_Integer = 1,
  LDOM_AsciiFree = 2,
  LDOM_AsciiDoc = 3,
  LDOM_AsciiDocClear = 4,
  LDOM_AsciiHashed = 5,
};

enum class LDOM_Node_NodeType {
  UNKNOWN = 0,
  ELEMENT_NODE = 1,
  ATTRIBUTE_NODE = 2,
  TEXT_NODE = 3,
  CDATA_SECTION_NODE = 4,
  COMMENT_NODE = 8,
};

enum class LDOM_OSStream_BOMType {
  BOM_UNDEFINED = 0,
  BOM_UTF8 = 1,
  BOM_UTF16BE = 2,
  BOM_UTF16LE = 3,
  BOM_UTF32BE = 4,
  BOM_UTF32LE = 5,
  BOM_UTF7 = 6,
  BOM_UTF1 = 7,
  BOM_UTFEBCDIC = 8,
  BOM_SCSU = 9,
  BOM_BOCU1 = 10,
  BOM_GB18030 = 11,
};

enum class LDOM_XmlReader_RecordType {
  XML_UNKNOWN = 0,
  XML_HEADER = 1,
  XML_DOCTYPE = 2,
  XML_COMMENT = 3,
  XML_START_ELEMENT = 4,
  XML_END_ELEMENT = 5,
  XML_FULL_ELEMENT = 6,
  XML_TEXT = 7,
  XML_CDATA = 8,
  XML_EOF = 9,
};

class LDOMBasicString {
public:
  LDOMBasicString();
  LDOMBasicString(int aValue);
  LDOMBasicString(const char* aValue);
  LDOMBasicString(const char* aValue, const opencascade::handle<LDOM_MemManager>& aDoc);
  LDOMBasicString(const char* aValue, int aLen, const opencascade::handle<LDOM_MemManager>& aDoc);
  LDOMBasicString_StringType Type() const;
  bool GetInteger(int& aResult) const;
  const char* GetString() const;
  bool equals(const LDOMBasicString& anOther) const;
};

class LDOMString : public LDOMBasicString {
public:
  LDOMString();
  LDOMString(int aValue);
  LDOMString(const char* aValue);
  const LDOM_MemManager& getOwnerDocument() const;
};

class LDOM_MemManager : public Standard_Transient {
public:
  LDOM_MemManager(int aBlockSize);
  void* Allocate(int aSize);
  const LDOM_MemManager& Self() const;
  const LDOM_BasicElement* RootElement() const;
  static const char* get_type_name();
  static const opencascade::handle<Standard_Type>& get_type_descriptor();
  const opencascade::handle<Standard_Type>& DynamicType() const;
};

class LDOM_Node {
public:
  LDOM_Node();
  const LDOM_MemManager& getOwnerDocument() const;
  bool isNull() const;
  LDOM_Node_NodeType getNodeType() const;
  %apply SWIGTYPE NETOCC_VIEW { LDOMString getNodeName };
  LDOMString getNodeName() const;
  %clear LDOMString getNodeName;
  %apply SWIGTYPE NETOCC_VIEW { LDOMString getNodeValue };
  LDOMString getNodeValue() const;
  %clear LDOMString getNodeValue;
  %apply SWIGTYPE NETOCC_VIEW { LDOM_Node getFirstChild };
  LDOM_Node getFirstChild() const;
  %clear LDOM_Node getFirstChild;
  %apply SWIGTYPE NETOCC_VIEW { LDOM_Node getLastChild };
  LDOM_Node getLastChild() const;
  %clear LDOM_Node getLastChild;
  %apply SWIGTYPE NETOCC_VIEW { LDOM_Node getNextSibling };
  LDOM_Node getNextSibling() const;
  %clear LDOM_Node getNextSibling;
  void removeChild(const LDOM_Node& aChild);
  void appendChild(const LDOM_Node& aChild);
  bool hasChildNodes() const;
  void SetValueClear() const;
};

class LDOM_Attr : public LDOM_Node {
public:
  LDOM_Attr();
  %apply SWIGTYPE NETOCC_VIEW { LDOMString getName };
  LDOMString getName() const;
  %clear LDOMString getName;
  %apply SWIGTYPE NETOCC_VIEW { LDOMString getValue };
  LDOMString getValue() const;
  %clear LDOMString getValue;
  void setValue(const LDOMString& aValue);
};

class LDOM_NodeList {
public:
  LDOM_NodeList();
  %apply SWIGTYPE NETOCC_VIEW { LDOM_Node item };
  LDOM_Node item(int arg0) const;
  %clear LDOM_Node item;
  int getLength() const;
};

class LDOM_Element : public LDOM_Node {
public:
  LDOM_Element();
  %apply SWIGTYPE NETOCC_VIEW { LDOMString getTagName };
  LDOMString getTagName() const;
  %clear LDOMString getTagName;
  %apply SWIGTYPE NETOCC_VIEW { LDOMString getAttribute };
  LDOMString getAttribute(const LDOMString& aName) const;
  %clear LDOMString getAttribute;
  %apply SWIGTYPE NETOCC_VIEW { LDOM_Attr getAttributeNode };
  LDOM_Attr getAttributeNode(const LDOMString& aName) const;
  %clear LDOM_Attr getAttributeNode;
  %apply SWIGTYPE NETOCC_VIEW_HELD { LDOM_NodeList getElementsByTagName };
  LDOM_NodeList getElementsByTagName(const LDOMString& aName) const;
  %clear LDOM_NodeList getElementsByTagName;
  void setAttribute(const LDOMString& aName, const LDOMString& aValue);
  void setAttributeNode(const LDOM_Attr& aNewAttr);
  void removeAttribute(const LDOMString& aName);
  %apply SWIGTYPE NETOCC_VIEW { LDOM_Element GetChildByTagName };
  LDOM_Element GetChildByTagName(const LDOMString& aTagName) const;
  %clear LDOM_Element GetChildByTagName;
  %apply SWIGTYPE NETOCC_VIEW { LDOM_Element GetSiblingByTagName };
  LDOM_Element GetSiblingByTagName() const;
  %clear LDOM_Element GetSiblingByTagName;
  void ReplaceElement(const LDOM_Element& anOther);
  %apply SWIGTYPE NETOCC_VIEW_HELD { LDOM_NodeList GetAttributesList };
  LDOM_NodeList GetAttributesList() const;
  %clear LDOM_NodeList GetAttributesList;
};

class LDOM_CharacterData : public LDOM_Node {
public:
  LDOM_CharacterData();
  %apply SWIGTYPE NETOCC_VIEW { LDOMString getData };
  LDOMString getData() const;
  %clear LDOMString getData;
  void setData(const LDOMString& aValue);
  int getLength() const;
};

class LDOM_Text : public LDOM_CharacterData {
public:
  LDOM_Text();
};

class LDOM_CDATASection : public LDOM_Text {
public:
  LDOM_CDATASection();
};

class LDOM_Comment : public LDOM_CharacterData {
public:
  LDOM_Comment();
};

class LDOM_Document {
public:
  LDOM_Document();
  LDOM_Document(const LDOM_MemManager& aMemManager);
  static LDOM_Document createDocument(const LDOMString& theQualifiedName);
  %apply SWIGTYPE NETOCC_VIEW { LDOM_Element createElement };
  LDOM_Element createElement(const LDOMString& theTagName);
  %clear LDOM_Element createElement;
  %apply SWIGTYPE NETOCC_VIEW { LDOM_CDATASection createCDATASection };
  LDOM_CDATASection createCDATASection(const LDOMString& theData);
  %clear LDOM_CDATASection createCDATASection;
  %apply SWIGTYPE NETOCC_VIEW { LDOM_Comment createComment };
  LDOM_Comment createComment(const LDOMString& theData);
  %clear LDOM_Comment createComment;
  %apply SWIGTYPE NETOCC_VIEW { LDOM_Text createTextNode };
  LDOM_Text createTextNode(const LDOMString& theData);
  %clear LDOM_Text createTextNode;
  %apply SWIGTYPE NETOCC_VIEW { LDOM_Element getDocumentElement };
  LDOM_Element getDocumentElement() const;
  %clear LDOM_Element getDocumentElement;
  %apply SWIGTYPE NETOCC_VIEW_HELD { LDOM_NodeList getElementsByTagName };
  LDOM_NodeList getElementsByTagName(const LDOMString& theTagName) const;
  %clear LDOM_NodeList getElementsByTagName;
  bool isNull() const;
};

class LDOM_SBuffer {
public:
  LDOM_SBuffer(int theMaxBuf);
  const char* str() const;
  int Length() const;
  void Clear();
  int overflow(int c = -1);
  int underflow();
  long long xsputn(const char* s, long long n);
};

class LDOM_OSStream {
public:
  LDOM_OSStream(int theMaxBuf);
  const char* str() const;
  int Length() const;
  void Clear();
};

class LDOMParser {
public:
  LDOMParser();
  LDOM_Document getDocument();
  bool parse(const char* aFileName);
  bool parse(std::istream& anInput, bool theTagPerStep = false, bool theWithoutRoot = false);
  const TCollection_AsciiString& GetError(TCollection_AsciiString& aData) const;
  LDOM_OSStream_BOMType GetBOM() const;
};

class LDOM_BasicNode {
public:
  bool isNull() const;
  LDOM_Node_NodeType getNodeType() const;
  const LDOM_BasicNode* GetSibling() const;
};

class LDOM_BasicAttribute : public LDOM_BasicNode {
public:
  LDOM_BasicAttribute();
  const char* GetName() const;
  const LDOMBasicString& GetValue() const;
};

class LDOM_BasicElement : public LDOM_BasicNode {
public:
  LDOM_BasicElement();
  const char* GetTagName() const;
  const LDOM_BasicNode* GetFirstChild() const;
  const LDOM_BasicNode* GetLastChild() const;
  const LDOM_BasicAttribute& GetAttribute(const LDOMBasicString& aName, const LDOM_BasicNode* aLastCh) const;
};

class LDOM_BasicText : public LDOM_BasicNode {
public:
  LDOM_BasicText();
  const LDOMBasicString& GetData() const;
};

class LDOM_CharReference {
public:
  LDOM_CharReference();
};

class LDOM_DocumentType {
public:
  LDOM_DocumentType();
};

class LDOM_LDOMImplementation {
public:
  LDOM_LDOMImplementation();
  static LDOM_Document createDocument(const LDOMString& aNamespaceURI, const LDOMString& aQualifiedName, const LDOM_DocumentType& aDocType);
};

class LDOM_XmlReader {
public:
  LDOM_BasicElement& GetElement() const;
  LDOM_OSStream_BOMType GetBOM() const;
};

class LDOM_XmlWriter {
public:
  LDOM_XmlWriter(const char* theEncoding = nullptr);
  void SetIndentation(int theIndent);
  void Write(std::ostream& theOStream, const LDOM_Document& theDoc);
  void Write(std::ostream& theOStream, const LDOM_Node& theNode);
};
