// SPDX-FileCopyrightText: 2026 Paul Büchner
// SPDX-License-Identifier: MIT

/* TColGeom2d: generated by netocc-gen from OCCT 8.0.1. Don't edit; change the generator or its config. */
%module TColGeom2dModule

%include "NetOcc.i"

%{
#include <TColGeom2d_module.hxx>
%}

#ifndef SWIGIMPORTED
%import "GeomAbs.i"
%import "Standard.i"
%import "NCollection.i"
%import "TCollection.i"
%import "TColStd.i"
%import "gp.i"
%import "TColgp.i"
%import "Geom2d.i"
%import "Geom2dEval.i"
#endif
%netocc_csimports(using OCC.Core.GeomAbs; using OCC.Core.Standard; using OCC.Core.NCollection; using OCC.Core.TCollection; using OCC.Core.TColStd; using OCC.Core.gp; using OCC.Core.TColgp; using OCC.Core.Geom2d; using OCC.Core.Geom2dEval;)

%occt_array1(TColGeom2d_Array1OfBSplineCurve, opencascade::handle<Geom2d_BSplineCurve>, Geom2d_BSplineCurve)
%occt_array1(TColGeom2d_Array1OfBezierCurve, opencascade::handle<Geom2d_BezierCurve>, Geom2d_BezierCurve)
%occt_array1(TColGeom2d_Array1OfCurve, opencascade::handle<Geom2d_Curve>, Geom2d_Curve)
%occt_sequence(TColGeom2d_SequenceOfBoundedCurve, opencascade::handle<Geom2d_BoundedCurve>, Geom2d_BoundedCurve)
%occt_sequence(TColGeom2d_SequenceOfCurve, opencascade::handle<Geom2d_Curve>, Geom2d_Curve)
%occt_sequence(TColGeom2d_SequenceOfGeometry, opencascade::handle<Geom2d_Geometry>, Geom2d_Geometry)
%occt_harray1(TColGeom2d_HArray1OfBSplineCurve, opencascade::handle<Geom2d_BSplineCurve>, Geom2d_BSplineCurve)
%occt_harray1(TColGeom2d_HArray1OfCurve, opencascade::handle<Geom2d_Curve>, Geom2d_Curve)
%occt_hsequence(TColGeom2d_HSequenceOfBoundedCurve, opencascade::handle<Geom2d_BoundedCurve>, Geom2d_BoundedCurve)
