// SPDX-FileCopyrightText: 2026 Paul Büchner
// SPDX-License-Identifier: MIT

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;

//
using NetOcc.Generator.Emit;

namespace NetOcc.Generator;

/// <summary>
/// Reads OCCT's own module/toolkit/package lists and writes config/toolkits.yaml. Sources (all
/// generated by OCCT, same <c>set(NAME items...)</c> format): <c>src/MODULES.cmake</c>,
/// <c>src/&lt;Module&gt;/TOOLKITS.cmake</c>, <c>src/&lt;Module&gt;/&lt;TK&gt;/PACKAGES.cmake</c>.
/// </summary>
internal static partial class Bootstrap
{
  // Draw is OCCT's test harness
  private static readonly HashSet<string> SkippedModules = ["Draw"];

  /// <param name="output">config/toolkits.yaml.</param>
  public static int Run(string occtSource, string output, TextWriter log)
  {
    var src = Path.Combine(occtSource, "src");
    if (!File.Exists(Path.Combine(src, "MODULES.cmake")))
    {
      throw new InvalidOperationException(
        $"netocc-gen bootstrap: {src}/MODULES.cmake not found (pass the OCCT source root)");
    }

    var version = ReadVersion(Path.Combine(occtSource, "adm", "cmake", "version.cmake"));
    var yaml = new StringBuilder()
      .AppendLine($"# Generated by `netocc-gen bootstrap` from OCCT {version}: src/MODULES.cmake,")
      .AppendLine(
        "# src/<Module>/TOOLKITS.cmake, src/<Module>/<TK>/PACKAGES.cmake. Do not edit; re-run on OCCT upgrades.")
      .AppendLine($"occt: {version}")
      .AppendLine("modules:");

    int toolkits = 0, packages = 0;
    foreach (var module in ReadList(Path.Combine(src, "MODULES.cmake"))
               .Where(m => !SkippedModules.Contains(m)))
    {
      yaml.AppendLine($"  {module}:");
      foreach (var toolkit in ReadList(Path.Combine(src, module, "TOOLKITS.cmake")))
      {
        var list = ReadList(Path.Combine(src, module, toolkit, "PACKAGES.cmake"));
        yaml.AppendLine($"    {toolkit}: [{string.Join(", ", list)}]");
        toolkits++;
        packages += list.Count;
      }
    }

    Directory.CreateDirectory(Path.GetDirectoryName(Path.GetFullPath(output))!);
    File.WriteAllText(output, GeneratedText.Lf(yaml.ToString()));
    log.WriteLine(
      $"netocc-gen: OCCT {version}: {toolkits} toolkits, {packages} packages -> {output}");
    return 0;
  }

  /// <summary>Items of the single <c>set(NAME item item ...)</c> in an OCCT list file.</summary>
  private static List<string> ReadList(string path)
  {
    var match = SetCommand().Match(File.ReadAllText(path));
    if (!match.Success)
    {
      throw new InvalidDataException($"no set(...) list in {path}");
    }

    return
    [
      .. match.Groups["items"]
        .Value.Split((char[])[' ', '\t', '\r', '\n'], StringSplitOptions.RemoveEmptyEntries)
    ];
  }

  // OCC_VERSION_MAJOR, _MINOR and _MAINTENANCE of adm/cmake/version.cmake: every module is stamped
  // with it, so a part that's missing fails here rather than in build.py
  private static string ReadVersion(string path)
  {
    var parts = VersionPart()
      .Matches(File.ReadAllText(path))
      .ToDictionary(m => m.Groups["part"].Value, m => m.Groups["value"].Value);
    return string.Join(
      ".",
      ((string[])["MAJOR", "MINOR", "MAINTENANCE"]).Select(part => parts.GetValueOrDefault(part)
                                                             ?? throw new InvalidDataException(
                                                               $"{path}: no OCC_VERSION_{part}")));
  }

  [GeneratedRegex(@"set\s*\(\s*\w+(?<items>[^)]*)\)", RegexOptions.Singleline)]
  private static partial Regex SetCommand();

  [GeneratedRegex(@"set\s*\(\s*OCC_VERSION_(?<part>MAJOR|MINOR|MAINTENANCE)\s+(?<value>\d+)\s*\)")]
  private static partial Regex VersionPart();
}
