// SPDX-FileCopyrightText: 2026 Paul Büchner
// SPDX-License-Identifier: MIT

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

//
using NetOcc.Generator.Model;

namespace NetOcc.Generator.Emit;

/// <summary>
/// A module's C++ headers: the aggregate one its .i includes, and the flat names of its nested and
/// namespace types.
/// </summary>
internal static class ModuleHeaders
{
  /// <summary>
  /// The header with the C++ aliases of a package's nested and namespace types (<c>using
  /// Geom_Curve_ResD1 = Geom_Curve::ResD1;</c>).
  /// </summary>
  public static string NestedHeaderOf(string package) => $"{package}_nested.hxx";

  // the flat names the generated code uses for nested and namespace types, as C++ aliases of the
  // real ones
  public static string? Nested(PackageModel package)
  {
    // class template instances no alias names too, under their flat names, with the headers of
    // their arguments
    List<(string Name, string Qualified, IEnumerable<string> Headers)> nested =
    [
      .. package.Enums.Where(e => e.QualifiedName is not null)
        .Select(e => (e.Name, e.QualifiedName!, (IEnumerable<string>)[e.Header])),
      .. package.Classes.Where(c => c.QualifiedName is not null)
        .Select(c => (c.Name, c.QualifiedName!, (IEnumerable<string>)[c.Header])),
      .. package.Classes.Where(c => c.Instance is not null)
        .Select(c => (c.Name, c.Instance!.Alias ?? c.Instance.Spelling,
                  c.Instance.Includes.AsEnumerable())),
    ];
    if (nested.Count == 0)
    {
      return null;
    }

    var text = new StringBuilder(GeneratedText.Header)
      .AppendLine(
        $"// Flat names of the nested and namespace types of {package.Name} for the NetOcc SWIG modules: generated by netocc-gen, don't edit")
      .AppendLine("#pragma once");
    foreach (var header in nested.SelectMany(n => n.Headers)
               .Distinct()
               .Order(StringComparer.Ordinal))
    {
      text.AppendLine($"#include <{header}>");
    }

    text.AppendLine();
    foreach (var (name, qualified, _) in nested)
    {
      text.AppendLine($"using {name} = {qualified};");
    }

    return text.ToString();
  }

  // the module's aggregate header: the preludes and the headers of the types it uses, then its own,
  // then its nested names
  public static string Module(PackageModel package, IReadOnlyList<string> prelude,
                              IEnumerable<string> foreignHeaders, bool hasNested)
  {
    var text = new StringBuilder(GeneratedText.Header)
      .AppendLine(
        $"// Aggregate header for the NetOcc SWIG module {package.Name}: generated by netocc-gen, don't edit")
      .AppendLine("#pragma once");
    // the types the package uses first: some OCCT headers miss includes they need. Names compare as
    // Windows' file names
    var own = new HashSet<string>(package.Headers, StringComparer.OrdinalIgnoreCase);
    var foreign = foreignHeaders.Where(h => !own.Contains(h))
      .Distinct(StringComparer.OrdinalIgnoreCase)
      .Order(StringComparer.Ordinal);
    foreach (var header in prelude.Concat(foreign)
               .Distinct(StringComparer.OrdinalIgnoreCase)
               .Concat(package.Headers))
    {
      text.AppendLine($"#include <{header}>");
    }

    if (hasNested)
    {
      text.AppendLine($"#include <{NestedHeaderOf(package.Name)}>");
    }

    return text.ToString();
  }
}
