// SPDX-FileCopyrightText: 2026 Paul Büchner
// SPDX-License-Identifier: MIT

// Flat names of the nested and namespace types of OpenGl for the NetOcc SWIG modules: generated by netocc-gen, don't edit
#pragma once
#include <NCollection_DataMap.hxx>
#include <NCollection_DefaultHasher.hxx>
#include <NCollection_Shared.hxx>
#include <OpenGl_Resource.hxx>
#include <Standard_Handle.hxx>
#include <TCollection_AsciiString.hxx>

using OpenGl_Context_OpenGl_ResourcesMap = OpenGl_Context::OpenGl_ResourcesMap;
